version: '3.8'
  
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    hostname: rabbitmq3-management-master
    ports:
      - "5672:5672"     # Default AMQP port
      - "15672:15672"   # Management UI port
    environment:
      RABBITMQ_ERLANG_COOKIE: "rabbitmq_cookie"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "Twers@sephora2023"
      #RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: '-rabbitmq_management path_prefix "/rabbitmq"'
    volumes:
      #- ./rabbitmq-config:/etc/rabbitmq
      - "./rabbitmq_data:/var/lib/rabbitmq"

volumes:
  rabbitmq_data:
