apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: dev-rcp
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-id: "lb-xxx"
    service.beta.kubernetes.io/alicloud-loadbalancer-cert-id: "511xxx"
    service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: "true"
    service.beta.kubernetes.io/alicloud-loadbalancer-protocol-port: "https:443"
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 443
      targetPort: 80
