apiVersion: v1
kind: ConfigMap
metadata:
  name: recon-backend-app-dev
data:
  application-dev.yml: |
    spring:
      datasource:
        url: jdbc:mysql://xxx.rds.aliyuncs.com:3306/xxx
        driverClassName: com.mysql.cj.jdbc.Driver
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}
      servlet:
        multipart:
          max-file-size: 100MB
          max-request-size: 100MB
    #  flyway:
    #    ignoreMissingMigrations: true 
    #    outOfOrder: true
      redis:
        host: xxx.rds.aliyuncs.com
        username: ${REDIS_USERNAME}
        password: ${REDIS_PASSWORD}
    swagger-ui:
      server:
        url: https://xxx.com/api/