server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.239.40.211:3100/loki/api/v1/push

scrape_configs:
  - job_name: reconn-dev
    static_configs:
    - targets:
        - localhost
      labels:
        job: applog-dev
        __path__: /home/chn-app-ops/app-log/*log